#!/system/bin/sh
export PREFIX=/data/local/tmp/runner/usr
export HOME=$PREFIX/home
export TMPDIR=$PREFIX/tmp
export PATH=$PATH:$PREFIX/bin:$PREFIX/bin/applets
if [ ! -z $LD_LIBRARY_PATH ]; then
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib
else
  export LD_LIBRARY_PATH=$PREFIX/lib
fi
chmod 777 -R $PREFIX

# 添加App内设置的环境
if [ -r $PREFIX/etc/app_env.list ]; then
  for i in $(cat $PREFIX/etc/app_env.list); do
    export $i
  done
fi
unset i

# 加载profile.d下的所有sh配置
for i in $PREFIX/etc/profile.d/*.sh; do
  if [ -r $i ]; then
    . $i
  fi
done
unset i

# 加载bash配置
if [ "$(basename $0)" = "bash" ]; then
    BASH=true
    SHELL=$0
fi

if [ "$BASH" ]; then
  if [[ "$-" = *"i"* ]]; then
    if [ -r $PREFIX/etc/bash.bashrc ]; then
        . $PREFIX/etc/bash.bashrc
    fi
    if [ -r $HOME/.bashrc ]; then
        . $HOME/.bashrc
    fi
  fi
fi